avalanche/benchmarks/classic/stream51.py, avalanche/benchmarks/datasets/stream51/stream51.py, avalanche/benchmarks/datasets/stream51/stream51_data.py
=> Added and verified auto-download functionality for Stream-51

avalanche/evaluation/__init__.py, avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/__init__.py, avalanche/logging/__init__.py, avalanche/logging/interactive_logging.py, avalanche/logging/strategy_logger.py, avalanche/logging/tensorboard_logger.py, avalanche/logging/text_logging.py, examples/ewc_mnist.py
=> Improved logging and evaluation modules documentation

README.md
Update imports so code does not break.
=> Updating Quick Example

avalanche/evaluation/metrics/confusion_matrix.py
The static methods have been moved within standalone class.
=> Minor refactoring of Confusion Matrix class

avalanche/evaluation/metrics/forgetting.py, examples/wandb_logger.py
Also updated wandb example with stream forgetting metric
=> Minor bug fix in forgetting 

README.md
=> Beautifyed README file.

avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/core50/core50_data.py, environment-dev.yml, environment.yml, setup.py
This PR brings an efficiency improvement for CORe50 which was downloading additional data not strictly needed for the PyTorch dataset. Now the download should be almost twice as fast.
=> CORe50 efficiency update + minor dep reordering

README.md
Aesthetic Changes to the README + image contributors added at the end of the readme.md.
=> Aesthetic Changes to the README + image contributors 

avalanche/benchmarks/classic/ccub200.py, avalanche/benchmarks/datasets/cub200/cub200.py
This PR replaces the current implementation of the CUB 200 dataset with one that crops the image given the bounding box found in the dataset archive.
Solves #506
=> Implementation of CUB200 (with bounding box cropping)

notebooks/06_loggers.ipynb
Updated documentation with metric `global counter` description.
=> Added global counter description

notebooks/03_benchmarks.ipynb
Fixed benchmarks notebook (MNIST download, tensors_scenario).
Switched initial example to SplitMNIST.
Cleared cells outputs.
Added some nice prints.
=> Fixed benchmarks notebook

avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, avalanche/benchmarks/scenarios/new_instances/ni_scenario.py, avalanche/benchmarks/scenarios/scenario_utils.py, avalanche/benchmarks/utils/avalanche_dataset.py, tests/test_mnist_benckmarks.py
=> Fixed #572, added some utils in AvalancheDataset

avalanche/logging/wandb_logger.py, examples/wandb_logger.py
=> W&B Logger updated docstring and parameters

avalanche/evaluation/metrics/cpu_usage.py, avalanche/evaluation/metrics/timing.py, examples/eval_plugin.py
=> Minor bug fix on epoch time

avalanche/benchmarks/utils/avalanche_dataset.py, tests/test_avalanche_dataset.py
Fixes an issue with the hierarchy flattening procedure in `AvalancheConcatDataset` as demonstrated in #623.
This should enable for #616 and #623 to continue.
=> Fixed issue in hierarchy flattening procedure (AvalancheConcatDataset)

avalanche/benchmarks/classic/core50.py, avalanche/benchmarks/classic/stream51.py, avalanche/benchmarks/datasets/__init__.py, avalanche/benchmarks/datasets/core50/__init__.py, avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/core50/core50_data.py, avalanche/benchmarks/datasets/cub200/cub200.py, avalanche/benchmarks/datasets/dataset_utils.py, avalanche/benchmarks/datasets/downloadable_dataset.py, avalanche/benchmarks/datasets/mini_imagenet/mini_imagenet.py, avalanche/benchmarks/datasets/openloris/openloris.py, avalanche/benchmarks/datasets/openloris/openloris_data.py, avalanche/benchmarks/datasets/stream51/stream51.py, avalanche/benchmarks/datasets/stream51/stream51_data.py, avalanche/benchmarks/datasets/tiny_imagenet/tiny_imagenet.py, avalanche/benchmarks/generators/scenario_generators.py, avalanche/benchmarks/scenarios/generic_scenario_creation.py, avalanche/benchmarks/utils/datasets_from_filelists.py, docs/gitbook/from-zero-to-hero-tutorial/03_benchmarks.md, docs/gitbook/getting-started/learn-avalanche-in-5-minutes.md, tests/test_core50.py
This PR brings some improvements to datasets:
- Standardization of the download procedure
- Utility method to get the default directory of a dataset
- Added some MD5 checksums
- Uniform default values of some parameters
This is part of the effort to make the front-facing API of the benchmarks module more uniform (#557).
=> Standardization of datasets

avalanche/benchmarks/scenarios/generic_cl_scenario.py, avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, tests/test_nc_sit_scenario.py
This PR fixes an anomaly with the `classes_in_exp_range` method.
This also removes a deprecated usage linked to how `classes_in_exp_range` obtains the list of classes.
Fixes #642
=> Fixed issue #642

avalanche/training/strategies/joint_training.py, examples/joint_training.py, tests/training/test_strategies.py
Bug fix.
Also, now it raises an error when `JointTraining` is trained more than once.
=> FIX JointTraining off-by-one data concatenation

avalanche/training/plugins/__init__.py, avalanche/training/plugins/gss_greedy.py, avalanche/training/strategies/strategy_wrappers.py, examples/gss_mnist.py
Hi,
I added the Gss_greedy strategy and a test file in the example folder, to get the same results as the paper:
https://arxiv.org/abs/1903.08671
=> Gss implementation

avalanche/training/plugins/gss_greedy.py
Hi, 
there was a typo on a function of gss_greedy plugin, causing an error in the torch function `multimodal`.
This PR will fix this problem.
=> Gss correction

avalanche/models/dynamic_modules.py, avalanche/models/pnn.py, avalanche/training/plugins/ewc.py, avalanche/training/plugins/lwf.py, avalanche/training/strategies/strategy_wrappers.py, tests/training/test_strategies.py
=> FIX forward_all_tasks

avalanche/logging/csv_logger.py, avalanche/logging/strategy_logger.py, avalanche/logging/tensorboard_logger.py, avalanche/logging/text_logging.py, avalanche/logging/wandb_logger.py, avalanche/training/plugins/cwr_star.py, avalanche/training/plugins/evaluation.py
I noticed that the count of encountered patterns for each class is not updated in CWR*. This PR fixes the problem. 
The problem affected only NIC scenarios, so current examples should be fine.
@lrzpellegrini let me know if I misunderstood the CWR* behavior.
=> Updated pastj after experience in CWR* and added support for logging metrics returning dictionary

notebooks/from-zero-to-hero-tutorial/04_training.ipynb
Just changing from From strenght to strength.
=> Microscopic Typo

avalanche/training/plugins/agem.py, avalanche/training/plugins/gem.py
GEM now works with multi-head by setting to zero the gradient of unused heads, same as for A-GEM.
Model forward has been replaced with avalanche-forward to take support multitask modules.
=> Fix GEM for multi-head

docs/gitbook/README.md
Fixed refactoring issues with documentation of `Without Avalanche` tab. 
https://github.com/ContinualAI/avalanche/issues/860#issue-1086975505
=> GitBook: fixed a bug in documentation

notebooks/from-zero-to-hero-tutorial/03_benchmarks.ipynb
=> Fix bug in Zero to Hero Benchmarks Tutorial

avalanche/training/strategies/joint_training.py
Added `_eval_streams` as strategy property, like in `BaseStrategy`.
=> Fixed periodic eval in joint training

avalanche/models/simple_mlp.py
This pull request fixes the probability of the `Dropout` hidden layer in the `SimpleMLP` class.
=> MLP dropout rate

avalanche/benchmarks/utils/data_loader.py, avalanche/training/plugins/replay.py, tests/test_dataloaders.py
This PR adds new options to  ReplayDataLoader and ReplayPlugin that enable custom data-memory ratios.
=> Update ReplayPlugin and ReplayDataLoader

notebooks/from-zero-to-hero-tutorial/02_models.ipynb, notebooks/from-zero-to-hero-tutorial/03_benchmarks.ipynb, notebooks/from-zero-to-hero-tutorial/04_training.ipynb, notebooks/from-zero-to-hero-tutorial/05_evaluation.ipynb, notebooks/from-zero-to-hero-tutorial/06_loggers.ipynb, notebooks/from-zero-to-hero-tutorial/07_putting-all-together.ipynb, notebooks/from-zero-to-hero-tutorial/08_extending-avalanche.ipynb, notebooks/from-zero-to-hero-tutorial/09_contribute-to-avalanche.ipynb, notebooks/how-tos/avalanchedataset/advanced-transformations.ipynb, notebooks/how-tos/avalanchedataset/creating-avalanchedatasets.ipynb, notebooks/how-tos/avalanchedataset/preamble-pytorch-datasets.ipynb, notebooks/how-tos/dataloading_buffers_replay.ipynb
Now all the notebooks use the beta version of avalanche installed with pip.
Closes #913
=> Modified avalanche installation in notebooks to beta version

avalanche/benchmarks/datasets/lvis/lvis.py, avalanche/evaluation/metric_utils.py, avalanche/training/templates/base.py, avalanche/training/templates/base_sgd.py, avalanche/training/templates/supervised.py, examples/detection_challenge.py, examples/tensorboard_logger.py, examples/tvdetection/engine.py, examples/tvdetection/lvis_eval.py
implementation of the object detection template. This is a refactoring of `train_one_epoch` and `lvis_evaluate` which uses Avalanche templates. Metric/logging logic is still missing (notice that this is implemented is several places in the original functions).
I put it in `detection_challenge.py` for the moment, to keep the old file for reference. We can delete it once the refactor is completed.
=> Detection template

avalanche/training/supervised/__init__.py, avalanche/training/supervised/lamaml.py, examples/lamaml_cifar100.py
Results for the same model (just replaced the final head with a MultiTask head instead of output masking):
CIFAR-100 (3 conv + 3 linear / no dropout or bn):
this implementation: ~0.69, in the paper: 0.70
TinyImageNet (4 conv + 3 linear / no dropout or bn):
this implementation: ~0.64, in the paper: 0.66
=> LaMAML Strategy

avalanche/benchmarks/classic/clear.py, avalanche/benchmarks/datasets/clear/__init__.py, avalanche/benchmarks/datasets/clear/clear.py, avalanche/benchmarks/datasets/clear/clear_data.py, examples/clear.py
add clear100(cvpr2022 workshop verision) split to avalanche along with clear10
=> [add] clear100_cvpr2022 workshop split 

notebooks/getting-started/learn-avalanche-in-5-minutes.ipynb
Trigger github action to copy notebook
=> Fake commit to copy notebook

.github/workflows/environment-update.yml, .github/workflows/test-coverage-coveralls.yml, .github/workflows/unit-test.yml, avalanche/training/plugins/cope.py, setup.py
Added support for python 3.10. It works in a fresh environment I created locally.
Added warning for COPE since it is not working currently.
=> Support py3.10 and warning for cope

extra_dependencies.txt, setup.py
This is related to #1062 and makes extra dependencies working by hard-coding them into setup.py
=> Moved extra dependencies to setup.py

MANIFEST.in, extra_dependencies.txt, setup.py
Adding MANIFEST.in did the trick. Thanks @ggraffieti 
Closes #1062
=> Fixed extra dependencies build

avalanche/training/supervised/icarl.py
#1075 
The class_patterns are generated via eval batch size
=> Fix bug, avoid OOM

avalanche/training/supervised/ar1.py
This PR fixes AR1 freezing the whole model by default and allows to choose the incremental learning rate, making the implementation closer to the original at https://github.com/vlomonaco/ar1-pytorch
With these fixes I am able to nearly replicate the results of the original github on CORe50.
=> Make AR1 closer to the original implementation

avalanche/benchmarks/utils/classification_dataset.py, avalanche/evaluation/metrics/accuracy.py, avalanche/training/templates/base_sgd.py, examples/clear_linear.py, examples/task_metrics.py
=> update and fix avl examples

.github/workflows/unit-test.yml
This adds an additional check in the unit test action to check if optional dependencies are actually not needed to run parts that do not need them.
=> Added optional dependencies test in unit test action

examples/hf_datawrapper.py, examples/nlp_nmt.py, examples/nlp_qa.py
Examples on how to use Avalanche for Natural Language Processing. Question answering example added. HuggingFace dataset wrapper added.
=> New Question Answering example. New wrapper for Huggingface Datasets

avalanche/benchmarks/scenarios/new_classes/nc_scenario.py
The details for this PR are documented in issue #1335
=> Speed up nc_scenario for larger datasets

avalanche/evaluation/metrics/cumulative_accuracies.py
I removed the necessity to access task boundaries
=> change to cumulative accuracy

avalanche/training/regularization.py, avalanche/training/supervised/__init__.py, avalanche/training/supervised/er_aml.py, tests/training/test_strategies.py
Implementation of er-aml criterion of the paper: https://openreview.net/forum?id=N8MaByOzUfb
=> er-aml implementation

notebooks/from-zero-to-hero-tutorial/04_training.ipynb
This PR adds new animation for the execution steps  of a Naive strategy extended with the EWC plugin.
=> Update FZTH tutorials

notebooks/how-tos/dataloading_buffers_replay.ipynb
main changes:
-    ` storage_p.buffer.targets ` gives error, so change to `storage_p.buffer.targets.uniques`
-  When creating custom plugin, i guess `StrategyPlugin` is depricated, so change it to `SupervisedPlugin`
=> fix dataloading_buffers_replay.ipynb notebook

notebooks/from-zero-to-hero-tutorial/02_models.ipynb, notebooks/from-zero-to-hero-tutorial/03_benchmarks.ipynb, notebooks/from-zero-to-hero-tutorial/04_training.ipynb, notebooks/from-zero-to-hero-tutorial/05_evaluation.ipynb, notebooks/from-zero-to-hero-tutorial/06_loggers.ipynb, notebooks/from-zero-to-hero-tutorial/07_putting-all-together.ipynb, notebooks/from-zero-to-hero-tutorial/08_extending-avalanche.ipynb
This PR updates the FZTH notebooks for the new release.
The only part that has changed is the last cell of `04_training`: `AvalancheConcatDataset` -> `concat_datasets`.
=> FZTH Notebooks for the New Release

avalanche/training/plugins/early_stopping.py
Hi, working with EarlyStoppingPlugin I found out that it doesn't take into account the margin in "min" mode.
This quick fix should work (in the sense that is not more broken than the previous version) as I changed as little as possible, but there aren't tests for EarlyStoppingPlugin.
=> Fix early stopping plugin
