ContinualAI/avalanche

avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/forgetting.py, avalanche/evaluation/metrics/loss.py, avalanche/evaluation/metrics/mac.py, examples/eval_plugin.py
MAC metric is computed on a single pattern taken from the current minibatch.
It can be updated at the end of each training iteration, training epoch or at the end of each eval experience. This last option is needed because the model could use different components for each eval experience, so we need to provide a way to monitor also this case (this should reflect the MAC on the corresponding experience at training time).
This closes #338
=> Added MAC metric

avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/forgetting.py
Minor fix to use `strategy.experience.current_experience` instead of `strategy.training_exp_counter`.
=> Fixed experience id bug in Forgetting

avalanche/__init__.py
This is a hotfix for MNIST automatic download that will point the MNIST download link to an alternative mirror.
=> Hotfix for MNIST automatic download

avalanche/benchmarks/scenarios/generic_definitions.py, avalanche/evaluation/metrics/forgetting.py, avalanche/evaluation/metrics/gpu_usage.py, avalanche/evaluation/metrics/mac.py, avalanche/evaluation/metrics/ram_usage.py, avalanche/evaluation/metrics/timing.py, tests/test_metrics.py
`ExperienceForgetting` was the only metric without a general metric. I implemented `Forgetting` to be used as off-the-shelf general metric and updated `ExperienceForgetting` accordingly.
I updated tests to test general metrics. I still have to write tests for the plugin metrics, which are a bit more complex since they require integration with the training and evaluation loops.
=> Added general metric Forgetting, improved documentation and tests

avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metrics/__init__.py, avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/confusion_matrix.py, avalanche/evaluation/metrics/cpu_usage.py, avalanche/evaluation/metrics/disk_usage.py, avalanche/evaluation/metrics/forgetting.py, avalanche/evaluation/metrics/gpu_usage.py, avalanche/evaluation/metrics/loss.py, avalanche/evaluation/metrics/mac.py, avalanche/evaluation/metrics/mean.py, avalanche/evaluation/metrics/ram_usage.py, avalanche/evaluation/metrics/timing.py
This closes #418 
I also updated FZTH tutorial. 
The names of metric types are now `Standalone` metrics (subclass `Metric`) and `Plugin` metrics (subclass `PluginMetric`).
=> Added standalone and plugin metric name into API doc

avalanche/benchmarks/utils/avalanche_dataset.py, avalanche/benchmarks/utils/data_loader.py, avalanche/core.py, avalanche/evaluation/metric_definitions.py, avalanche/logging/interactive_logging.py, avalanche/logging/strategy_logger.py, avalanche/training/plugins/agem.py, avalanche/training/plugins/evaluation.py, avalanche/training/plugins/gdumb.py, avalanche/training/plugins/replay.py, avalanche/training/plugins/strategy_plugin.py, avalanche/training/strategies/ar1.py, avalanche/training/strategies/base_strategy.py, avalanche/training/strategies/cumulative.py, avalanche/training/strategies/joint_training.py, docs/gitbook/from-zero-to-hero-tutorial/3.-training.md, tests/test_dataloaders.py, tests/test_plugins.py
PR to update strategies to support the new `AvalancheDataset`. There are also some changes to the data adaptation phase.
- Convert data loaders to accept `AvalancheDataset`.
- create explicit `dataset_adaptation` phase.
- Added docstring for callbacks.
regarding point (2), this removes the old callback `adapt_dataset` with `before/after_data_adaptation` callbacks.
- makes it easier to write data adaptation strategies (e.g. cumulative and joint training)
- makes it easier to explain/understand strategies and callbacks.
`BaseStrategy` loops become:
```
train
train_exp  # for each experience
adapt_train_dataset
train_dataset_adaptation
make_train_dataloader
train_epoch  # for each epoch
```
Closes #452 #382.
=> update dataloader to use AvalancheDataset

avalanche/evaluation/metrics/forgetting.py, examples/eval_plugin.py
The StreamForgetting is implemented as the average of the forgetting over all experiences. A forgetting_metrics helper method is implemented to create both the StreamForgetting and ExperienceForgetting metrics. The use is exemplified in the examples/eval_plugin.py
=> StreamForgetting

avalanche/training/plugins/ewc.py
This PR fixes the case in which EWC is used on a model in which some parameters do not require gradients. Their importance is set to zero.
=> EWC do not compute importance for parameters without gradient

avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/confusion_matrix.py, avalanche/logging/tensorboard_logger.py, avalanche/logging/wandb_logger.py, avalanche/training/plugins/evaluation.py
This PR brings the following changes:
1. WandbLogger and Tensorboard logger now logs also matplotlib Figure and histogram
2. Confusion matrix is logged as a figure, not image. By default, the confusion matrix does not show numbers in the cell, to accommodate for medium / large number of classes. 
3. Confusion matrix now uses `num_classes` to fix the size of the confusion matrix for all the training and evaluation. This value is strict. The class documentation has been updated to explain the change.
4. The evaluation logger returns the plain metric dictionary instead of a copy. This is because matplotlib Figures cannot be deepcopied. This should not be a problem because loggers logs metrics instantly.
This closes #513
=> Add histogram and figure logging, fixed confusion matrix bug

avalanche/benchmarks/scenarios/generic_cl_scenario.py, avalanche/benchmarks/scenarios/generic_definitions.py, avalanche/benchmarks/scenarios/generic_scenario_creation.py, avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, avalanche/benchmarks/scenarios/new_instances/ni_scenario.py, tests/test_custom_streams.py
This PR implements the support for custom streams. Custom streams (validation, out-of-distribution, ...) are used by some benchmarks but as of now Avalanche only supports the 'train' and 'test' streams.
This also introduces the support for streams with varying lengths. Now Avalanche only supports train and test streams with the same amount of experiences (or 1 experience for test set). With this PR stream lengths will be unconstrained.
Resolves #332
Resolves #443
=> Support for custom streams

avalanche/models/simple_cnn.py
The `SimpleCNN` previously removes all the dimensions with size 1. This removed also batch size, which was instead needed.
This closes #524
=> Fixed bug before SimpleCNN classifier

avalanche/benchmarks/classic/cfashion_mnist.py
FMNIST transformations were the ones used in CIFAR-10. They produced an error when looping through the dataset. I kept only the `ToTensor` transformation, since I don't think FMNIST requires specific preprocessing.
@lrzpellegrini do I need to add also a normalization like in MNIST? If so, do you have the normalization coefficients? You can merge the PR as soon as you are ok with the changes. Let me know if there are any issues.
This solves #490
=> Fixed FMNIST transformations

avalanche/training/plugins/synaptic_intelligence.py, avalanche/training/strategies/strategy_wrappers.py
The Synaptic Intelligence implementation refers to a different paper than the original one. I clarified this fact in the plugin and strategy doc.
This closes #106
=> Added correct reference to the SI paper

examples/ar1.py, examples/lwf_mnist.py, examples/task_incremental.py
This PR simply sets num_workers=0 for all the examples and notebooks to avoid bugs on Windows.
Solves #510.
=> num_workers=0 for all the examples and notebooks

avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/confusion_matrix.py, avalanche/evaluation/metrics/cpu_usage.py, avalanche/evaluation/metrics/disk_usage.py, avalanche/evaluation/metrics/forgetting.py, avalanche/evaluation/metrics/gpu_usage.py, avalanche/evaluation/metrics/loss.py, avalanche/evaluation/metrics/mac.py, avalanche/evaluation/metrics/ram_usage.py, avalanche/evaluation/metrics/timing.py
I added `super` calls to correctly update the global counter for metrics.
This is related to #550
=> Fixed bug in global it counter

avalanche/benchmarks/classic/ccifar100.py
CIFAR-100 has different normalization stats than CIFAR-10. However, in the current implementation, the same stats were used for CIFAR-10 and CIFAR-100.
This commit fixes this issue.
Source for calculating stats: https://gist.github.com/weiaicunzai/e623931921efefd4c331622c344d8151
=> Fix wrong normalization statistics for CIFAR-100

avalanche/benchmarks/classic/cfashion_mnist.py
Fashion MNIST normalization stats are wrong in the current implementation.  
Source for calculating stats: https://gist.github.com/weiaicunzai/e623931921efefd4c331622c344d8151
=> Fix wrong normalization statistics for Fashion MNIST

avalanche/models/pytorchcv_wrapper.py, examples/pytorchcv_models.py, tests/test_models.py
Hi,
Closes #430 . This PR implement a pytorchcv wrapper to load various models. A general wrapper is available through `get_model`. For VGG, Resnet, DenseNet and Pyramidnet direct wrappers are provided.
A bit of explanation for the design choices:
- Initially I wanted to make sure that imagenet pre-trained models could be easily used for Cifar etc. However, this isn't as simple as changing input and output layers. Eg in Resnet, the structure of the convolutional layers also change because of the smaller input size. Since there is no straight-forward way, I would leave it up to the user to change models if required, such that no unexpected behavior is introduced.
- The choice of the networks (vgg, densenet, pryamidnet..)  is mostly based on the nets available for cifar10/100. 
- Not all …
=> pytorchcv wrapper

.github/workflows/test-coverage-coveralls.yml, .github/workflows/unit-test.yml, examples/wandb_logger.py, tests/test_high_level_generators.py
This PR improves the automatic testing of the project: 
- Using a docker image with pre-downloaded datasets, data no longer has to be downloaded every time the software is tested. This solves download issues (broken links, servers down, slow connection..) making the testing procedure more reliable. 
- Using a docker image with only python + conda installed increase the validity of testing since the environment is minimal and does not contain any unnecessary package. 
- Conda is now runned directly in the shell without relying on any additional action. This seems to have solved the slow environment creation with python 3.6 
- Fix download location for the data used during tests.
Now in the docker image are only contained the MNIST and tiny imagenet, cifar10 and cats_and_dogs will be …
=> Docker image with pre-downloaded datasets used in test

avalanche/benchmarks/classic/core50.py, avalanche/benchmarks/classic/openloris.py
CORe50 and OpenLORIS benchmarks were created by passing a single filelist representing the unique test experience. The new helpers expect a list to be passed even when a single filelist is used. Passing a string leads to an error during the creation of the benchmark.
This PR fixes that issue by wrapping the filelist path in a list.
=> Fix for CORe50 and OpenLORIS benchmarks.

avalanche/benchmarks/utils/data_loader.py, avalanche/training/plugins/agem.py, avalanche/training/plugins/cope.py, avalanche/training/plugins/replay.py, avalanche/training/strategies/base_strategy.py, examples/dataloader.py, tests/test_dataloaders.py
This PR updates dataloaders. Now BaseStrategy supports pytorch dataloaders. Custom dataloaders are provided for CL-specific features:
- TaskBalancedDataLoader
- GroupBalancedDataLoader
- ReplayDataLoader
BaseStrategy (and dataloaders) now supports arbitrary mini-batches of the form `<x, y, ..., t>`.
Closes #539.
=> BaseStrategy support for arbitrary mini-batches

avalanche/benchmarks/classic/ccifar10.py, avalanche/benchmarks/classic/ccifar100.py, avalanche/benchmarks/classic/ccub200.py, avalanche/benchmarks/classic/cfashion_mnist.py, avalanche/benchmarks/classic/cimagenet.py, avalanche/benchmarks/classic/cmnist.py, avalanche/benchmarks/classic/comniglot.py, avalanche/benchmarks/classic/ctiny_imagenet.py, avalanche/benchmarks/generators/benchmark_generators.py, avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, avalanche/benchmarks/scenarios/new_instances/ni_scenario.py, tests/test_cifar100_benchmarks.py, tests/test_cifar10_benchmarks.py, tests/test_fmnist_benckmarks.py, tests/test_mnist_benckmarks.py, tests/test_nc_sit_scenario.py, tests/unit_tests_utils.py
This PR implements a better handling of train and eval transformations for `ni_benchmark` and `nc_benchmark` helpers. Train and eval transformations can now be defined by passing them to these helpers.
Adapted classic benchmarks.
Added unit tests for FMnist and CIFAR benchmarks.
Better unit tests for MNIST benchmarks.
Fixes #575
Fixes #577
=> Better handling of transformations in ni/nc_benchmark

avalanche/training/strategies/base_strategy.py
This adds an explicit support for the `pin_memory` parameter in `BaseStrategy` (used when creating `DataLoader`s).
The default value for `pin_memory` is set to `True`.
=> Support for pin_memory in BaseStrategy

avalanche/core.py
This closes #548. The module cannot be moved into the training module due to circular dep. I just added a bit of doc. We will keep it here as a "sub-module" for now. It may be upgraded in a "sub-package" later on as we add functionalities.
=> Core Module Docstring Updated

avalanche/benchmarks/scenarios/generic_cl_scenario.py, avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, avalanche/benchmarks/scenarios/new_instances/ni_scenario.py, tests/test_core50.py, tests/test_generic_cl_scenario.py, tests/test_nc_mt_scenario.py, tests/test_nc_sit_scenario.py, tests/test_ni_sit_scenario.py
The `classes_in_this_experience` field of `GenericCLScenario` by default returned the list linked to the training stream. This made it difficult to obtain the list of classes for non-training experiences.
This PR introduces another way to use that field, which can now be used as:
```python
benchmark_instance.classes_in_experience[stream_name][exp_id]
```
The previous way to use this field is deprecated. The following:
```python
benchmark_instance.classes_in_experience[exp_id]  # Deprecated
```
still works, but a warning will be printed to stdout.
Fixes #593
=> Fix for #593

avalanche/benchmarks/generators/benchmark_generators.py, tests/test_high_level_generators.py
This PR introduces and helper that can be used to obtain a benchmark instance with a proper validation stream.
This simple helper `benchmark_with_validation_stream` takes an existing benchmark instance as an input and splits each experience in the train stream to obtain a valid stream with the same amount of experiences.
As of now no class balancing is used (as the helper must be general enough to handle non-classification tasks), but a custom splitting strategy can be employed as well.
The size of validation experiences can be set by passing an absolute size (int) or a relative size (float between 0 and 1).
Fixes #262
=> Validation stream creation helper

avalanche/logging/__init__.py, avalanche/logging/csv_logger.py, avalanche/training/strategies/base_strategy.py, examples/eval_plugin.py
This PR brings the `CSVLogger`: a logger which can be used to produce two files.
The training file lists for each epoch and experience the training and validation accuracies and losses.
The evaluation file lists for each training and evaluation experience the accuracy, loss and forgetting.
Important points which may reduce the value of this logger: 
this is quite a specific logger which assumes 
1) logging at least accuracy explicitly for each epoch and experience (maybe the logger name could be changed into `CSVClassificationLogger` but I don't like it very much). 
2) evaluation during training is performed only on the eval experience corresponding to the training one.
The example `eval_plugin` shows how to use it and I could provide a separate one if needed. We could also think about …
=> Added csvlogger

.github/workflows/test-coverage-coveralls.yml, .github/workflows/unit-test.yml
- Conda installed pytorch 1.4 (and torchvision 0.5) in the environment with python 3.6
- The bug cannot be reproduced locally, but the conda version and the installed packages are the same, so I cannot speculate almost anything about the reason of this strange behavior. 
- This is just a quick patch to the problem (versions are now hardcoded into the workflows). 
- I will take care of a better handling of the dependencies as pointed out in issue #611
=> Fix bug with unit test on python 3.6

avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metric_results.py, avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/cpu_usage.py, avalanche/evaluation/metrics/disk_usage.py, avalanche/evaluation/metrics/gpu_usage.py, avalanche/evaluation/metrics/loss.py, avalanche/evaluation/metrics/mac.py, avalanche/evaluation/metrics/ram_usage.py, avalanche/evaluation/metrics/timing.py
This PR refactors most of the existing metrics following the newly introduced `GenericPluginMetric`. This change does not affect neither the metric behavior nor the user interface.
Forgetting and confusion matrix metrics are still implemented through the `PluginMetric` class since they have a slightly more complex flow.
Now the generic plugin can be used to easily build new metrics.
=> Refactored metrics to follow a GenericPluginMetric class

avalanche/training/plugins/gdumb.py
Hello there, thanks for this cool package! :)
I think I've spotted a bug in GDumbPlugin, it fails to concatenate the samples due to a shape mismatch between `pattern` and `target`.  
Also, I think the current implementation is quite inefficient: for each new item,
it performed an entire concatenation with the current dataset.
This uses lists instead, and only concatenates once.
It also uses the task labels from each sample in the dataset, rather
the task label from the current experience, as there might be more
than one task in the dataset.
Signed-off-by: Fabrice Normandin <fabrice.normandin@gmail.com>
=> Fix bug in GDumbPlugin

avalanche/benchmarks/classic/core50.py, avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/core50/core50_data.py, tests/test_core50.py
This PR brings support for the Category-Level Classification in CORe50, partially tackling issue #547.
In particular it adds support for:
* Downloading additional data regarding the labels human-readable names.
* Changing the labels value for the basic CORe50 Dataset
* Generating category-level filelists for all the scenario
* Adding a new parameter to the classic benchmark to control the classification level (object-level vs category-level)
=> Adding Category-Level Classification Support for CORe50

avalanche/evaluation/metrics/confusion_matrix.py
`BaseStrategy.logits` was renamed to `BaseStrategy.mb_outputs`, but wandb confusion matrix plugin got forgotten.
=> [wandb] Fix Confusion Matrix Plugin

avalanche/logging/tensorboard_logger.py
PyTorch's `SummaryWriter` support writing logs directly to AWS S3 buckets and Google Cloud buckets if the path provided starts by `s3://` or `gs://`. (GS buckets are only supported if tensorflow is also installed https://github.com/pytorch/pytorch/issues/24468#issuecomment-549415705_)
We were not able to use this functionality previously because of the Path conversion. 
🐛  I also noticed that the last logs were often missing (flushing is done automatically every 2 min, and if we don't do it manually at the end then the non flushed logs are lost). Closing the writer in the logger destructor fixes that issue.
=> [TensorboardLogger] Add support for AWS and Gcloud buckets

avalanche/benchmarks/utils/avalanche_dataset.py, avalanche/training/plugins/replay.py, tests/training/test_replay.py
This extends the `ExperienceBalancedStoragePolicy` to be able to use different selection strategies. It expect the strategy to sort the exemplars, and so only need to be called the first time they are seen.
I implemented 3 strategies:
- Random selection (which was the previous behavior)
- Herding (as used in the [iCaRL paper](https://arxiv.org/pdf/1611.07725.pdf))
- Closest to center (in feature space)
[RWalk](https://arxiv.org/pdf/1801.10112.pdf) introduced other strategies, like entropy or distance to boundary decision, but herding and random seems to be the more used / best strategies.
=> [Replay] Add some memory selection strategies

avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/confusion_matrix.py
Implementing class order in CM #627 cc @AndreaCossu 
Here is an exemple of CM obtained with the new defaults:
I tried to implement it for W&B too, but it seems that the UI re-order the classes alphabetically, so it doesn't work. We could prefix with the relative number (0. Class 3 / 1. Class 5 / 2. Class 9, ...) to get it sorted correctly
=> [evaluation] (CM) implement relative class order in confusion matrix

avalanche/benchmarks/classic/core50.py, avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/core50/core50_data.py
This PR expands CORe50 functionalities partially addressing #547.
In particular:
* It adds support to work with a CORe50 32x32 as raw data (no on-the-fly transformations). This both for the classic benchmark and the core dataset to be used with generators.
* Faster automatic download if the mini option is enabled (no need to download the 128x128 version). 128x128 images can still be download with setting the "extra" param to True in `download_core50(self, extra=False)`.
=> CORe50 Mini Option Added

avalanche/models/__init__.py, avalanche/models/dynamic_modules.py, avalanche/models/icarl_resnet.py, avalanche/models/ncm_classifier.py, avalanche/training/losses.py, avalanche/training/plugins/icarl.py, avalanche/training/strategies/icarl.py, examples/icarl.py, tests/test_models.py, tests/training/test_losses.py, tests/training/test_strategies.py
Implementation of iCaRL algorithm with an Avalanche plugin.
Issues:
- Should I add to Avalanche the ResNet, data augmentation and main.py needed to reproduce the paper results?
- There are some utilities classes needed by the plugin that are currently stored inside the same file (e.g. DistillationLoss, NCMClassifier). Maybe they could be moved somewhere else.
- Still working to avoid having to pass `diff_transform` to the plugin (the difference between test_transform and train_transform). It should be easy but some of the solution I've tried led to a decrease in performances.
Apart from that the plugin works and achieves the results reported by the paper.
=> added icarl plugin

avalanche/benchmarks/datasets/openloris/openloris.py, avalanche/benchmarks/datasets/openloris/openloris_data.py
This PR closes #617. It uses the new continualai vps with openloris mirrors to download the data.
This still needs to be tested since the vps is currently down.
=> OpenLORIS GDrive Links Changed to Avl VPS

avalanche/benchmarks/classic/ccifar10.py, avalanche/benchmarks/classic/ccifar100.py, avalanche/benchmarks/classic/ccub200.py, avalanche/benchmarks/classic/cfashion_mnist.py, avalanche/benchmarks/classic/cimagenet.py, avalanche/benchmarks/classic/cinaturalist.py, avalanche/benchmarks/classic/classic_benchmarks_utils.py, avalanche/benchmarks/classic/cmnist.py, avalanche/benchmarks/classic/comniglot.py, avalanche/benchmarks/classic/core50.py, avalanche/benchmarks/classic/ctiny_imagenet.py, avalanche/benchmarks/classic/openloris.py, avalanche/benchmarks/classic/stream51.py, avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/cub200/cub200.py, avalanche/benchmarks/datasets/dataset_utils.py, avalanche/benchmarks/datasets/downloadable_dataset.py, avalanche/benchmarks/datasets/openloris/openloris.py, avalanche/benchmarks/datasets/stream51/stream51.py, avalanche/benchmarks/datasets/tiny_imagenet/tiny_imagenet.py, avalanche/benchmarks/scenarios/new_classes/nc_scenario.py, tests/test_avalanche_dataset.py, tests/test_nc_sit_scenario.py
This PR completes the standardization of classic benchmarks. Parameter names should now be uniform across all classic benchmarks.
A small utility function has been added to quickly check if a benchmark is implemented correctly. All benchmarks now have a `__main__` section with a small test using that utility function.
This also fixes an unreported issue with PermutedOmniglot.
Closes #557
=> Standardization of classic benchmarks

avalanche/benchmarks/utils/avalanche_dataset.py, tests/test_avalanche_dataset.py, tests/test_custom_streams.py
Fixes an issue with task labels conversions. Task labels weren't properly converted to int when using the `AvalancheDataset` and `AvalancheConcatDataset` constructors. `AvalancheSubset` was not affected.
This also adds a small type hint fix for `AvalancheTensorDataset`.
Fixes #654
=> Fixes issue 654

avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/confusion_matrix.py, avalanche/training/strategies/base_strategy.py, tests/test_avalanche_dataset.py
This closes #657 , implementing @lrzpellegrini 's suggestion. 
The `isinstance(experience, Experience)` call is modified to `not isinstance(experience, Sequence)`.
=> Fixed isinstance on Base Strategy to enable benchmarks with task label per pattern

avalanche/benchmarks/generators/benchmark_generators.py, avalanche/benchmarks/scenarios/generic_benchmark_creation.py, avalanche/benchmarks/scenarios/generic_cl_scenario.py, avalanche/benchmarks/scenarios/generic_definitions.py, avalanche/benchmarks/scenarios/lazy_dataset_sequence.py, avalanche/benchmarks/scenarios/new_instances/ni_scenario.py, tests/test_generic_cl_scenario.py, tests/test_high_level_generators.py
This PR introduces the support for lazy streams (discussed in #600)
This PR introduces some changes on the internals of `GenericCLScenario` and adds proper helpers to support the creation of streams based on generator expressions or functions.
This also introduces the support for dropping the references to previous experiences to allow for a more fine-grained memory management (to be documented).
Beware that the helper used to create data incremental benchmarks and the helper used to create a validation stream will still work in non-lazy mode (will load all experiences at once). This behavior will be fixed in the future.
The behavior for non-lazy benchmarks will not be affected by these changes.
=> Support for lazily created streams

avalanche/training/plugins/early_stopping.py, avalanche/training/strategies/base_strategy.py, examples/all_mnist_early_stopping.py
Implementation of #664.
Maybe we could add the option to define the patience in terms of iterations instead of epochs, but I think that it can't be easily implemented for now since there is no simple way to keep track of the iteration count in the current training procedure.
=> Implement early-stopping

avalanche/training/strategies/base_strategy.py, avalanche/training/strategies/deep_slda.py, tests/training/test_strategies.py
This adresses the part about the disabled callbacks of #659 
> Disable callbacks
A big limitation of the plugin system is that the set of callbacks is fixed. Some strategies may skip some stages and break plugins as a result. The only example up to now is DeepSLDA, which does not use backprop, but there may be others in the future. It would be better if we could somehow add and remove callbacks for custom strategies. If a plugin implements a callback that the strategy does not support, it should raise an error.
Still need to do something more custom for the `GenericPluginMetric`, otherwise we will get a lot of false warnings, because it redefines (but not necessarily use, depending on the arguments passed) a lot of callbacks.
=> [training] Warn if using disabled callbacks in strategies

avalanche/benchmarks/generators/benchmark_generators.py, avalanche/benchmarks/scenarios/generic_cl_scenario.py, tests/test_high_level_generators.py
This PR introduces the support for lazy streams in the `benchmark_with_validation_stream` helper.
That helper is used to generate a benchmark instance in which the validation stream is added by splitting the train stream. If the train stream is lazily generated, then the resulting benchmark instance will have lazily generated `train` and `valid` streams.
This behavior is fully compatible with custom splitting strategies!
This partially covers #673.
The support for lazy streams in `data_incremental_benchmark` will be implemented in the future as it requires a major overhaul on the Avalanche internals.
=> Support for lazy streams in benchmark_with_validation_stream

avalanche/evaluation/metrics/mean.py, avalanche/evaluation/metrics/mean_scores.py, examples/mean_scores.py
To prepare #676 
This is a metric that was used to show bias toward new classes in the IL2M paper.
The scores of the true class are averaged by past and new classes.
- For the train plugin I only used the last epoch, the graphs are hard to read if we add more
- For the eval plugin the full stream needs to be considered, so that we can compare old and new classes
This is what I get for the simple example:
The `MeanScores` metric can be reused for the `IL2MPlugin`
Edit: Ready for review :)
=> [metrics] (MeanScores) Add a mean scores metrics inspired from IL2M

avalanche/training/plugins/agem.py, examples/gem_agem_mnist.py
A-Gem is now working (fixed gradient projection computation) and nearly matching the reported performance.
Updated the example providing the new numbers.
Best Jonas
=> fix-agem. resolved memory filling and grad proj

avalanche/training/plugins/ewc.py
This PR corrects a mistake that causes over-estimation of EWC Results. This is a common bug found in multiple github repos that implement EWC.
**The bug**:
For models such as AlexNet, SimpleCNN that do not have `batchnorm` layers, a forward pass through the model will not alter any parameters.
But for other models such as ResNet variants, there are batch norm layers. The forward pass causes change of batchnorm mean and standard deviation.
In this context, the `compute_importances` **should not** change the parameters. I observed the models before and after this function, and observed that it did. This also increases the results by `3-4%` sometimes.
**The fix**:
I have put a `model.eval()` so that the batchnorm stats are fixed and frozen.
=> Correct mistake in ewc.py

avalanche/training/plugins/ewc.py
Online EWC now performs better than Naive, as we expected. Additionally I have verified that the penalty is non-zero.
Resolves #728
=> Fix online EWC penalty calculation

avalanche/models/__init__.py, avalanche/models/base_model.py, avalanche/models/simple_mlp.py, avalanche/training/plugins/__init__.py, avalanche/training/plugins/lfl.py, avalanche/training/strategies/strategy_wrappers.py, examples/lfl_mnist.py, tests/training/test_strategies.py
I have implemented the LFL plugin from the paper [Less-Forgetful Learning](https://arxiv.org/abs/1607.00122) along with the strategy wrapper, and an example.
The LFL algorithm requires computing penalty euclidean loss with current and previous model features. To avoid model-specific modifications in the plugin (i.e flattening the input in case of MLP model), I have created a base abstract class `BaseModel `which requires implementing `get_features()` in its subclasses, as suggested by @AndreaCossu on Slack. 
Currently, I have only made the `SimpleMLP` class inherit this `BaseModel` for the example and test cases to work. The plugin will check if the model is an instance of this base class and will raise NotImplementedError if it is not. 
Kindly let me know if the implementation seems …
=> Added Less-Forgetful Learning LFL Plugin

avalanche/training/plugins/synaptic_intelligence.py
Results are no longer identical when the seed is identical implying that the surrogate loss (regularisation) is being used. However since it does not perform as well as I would expect I'm a little concerned that I might not have fixed it.
#734
=> Calculate loss before backpropogation

avalanche/models/__init__.py, avalanche/models/helper_method.py, tests/test_helper_method.py
I left both the method and the test in separate files for now, let me know if you want me to integrate them to existing ones.
I think its working quite well, however they are few things to be aware of.
In particular, one thing I could not get around ( but I don't think I should ), is to make pytorch return a state_dict totally ignoring the MultiTaskDecorator class. So the state dict it returns contains the two "modules" from this class which are the "model" object and the "classifier". In any case, if a user wants to load a state dict from a multi head model he won't be able to load it into the non-multi head equivalent so I don't think this is a problem. 
Another related problem will appear when accessing the names of the modules, since now calling something like model.named_modules() …
=> Added helper method to convert nn.Modules to multi-head models

notebooks/from-zero-to-hero-tutorial/03_benchmarks.ipynb
Old Link Leads to a 404:
https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder
The new link appears to be:
https://pytorch.org/vision/stable/datasets.html#torchvision.datasets.ImageFolder
=> Updated the old Dead Link to ImageFolder docs

avalanche/training/plugins/synaptic_intelligence.py, avalanche/training/strategies/strategy_wrappers.py
SI, like LwF, accepts one lambda for each experience.
If the number of experiences is greater than the number of lambdas, last lambda will be used for the remaining experiences.
=> Allow one lambda for experience in SI

avalanche/training/plugins/ewc.py
Workaround for PyTorch bug where RNN's on CUDA devices cannot run `backwards` in `eval` mode.
Sets all `nn.BaseRNN` modules in a model to `train` mode during the compute importances phase of EWC if on a CUDA device.
=> Fix #736 (CUDA bug with RNN's using EWC)

avalanche/logging/wandb_logger.py, examples/wandb_logger.py
WandBLogger now accepts as input a dictionary which can be helpful for cases where the hyperparameters are loaded as a dictionary from a file.
=> FIX config type in WandBLogger by accepting a plain dictionary as input

avalanche/benchmarks/scenarios/generic_cl_scenario.py, environment-dev.yml, environment.yml
This change is aimed at supporting [Avalanche-RL](https://github.com/ContinualAI/avalanche-rl/) fork by including `gym.Env` as a possible data type to be contained within experiences.
It enables Avalanche RL to utilize Avalanche benchmark module as a direct dependency without touching its source code.
I should also mention that OpenAI `gym` would now become a required dependency for Avalanche as well.
I'm very open to discuss this kind of change and evaluate any alternative options that I may overlooked in order to support benchmarks with `gym.Env` experiences .
=> Add support for gym.Env experiences  

avalanche/benchmarks/utils/avalanche_dataset.py, avalanche/benchmarks/utils/dataset_utils.py, avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metrics/accuracy.py, avalanche/evaluation/metrics/forgetting_bwt.py, avalanche/evaluation/metrics/forward_transfer.py, avalanche/evaluation/metrics/labels_repartition.py, avalanche/evaluation/metrics/mean.py, avalanche/evaluation/metrics/mean_scores.py
Under python 3.9 just importing the module causes an error "Protocols cannot be initialized".
The given error is found inside typing_extensions and warns the user about an invalid use of [protocols](https://www.python.org/dev/peps/pep-0544/): instantiation.
https://github.com/python/typing/blob/68e7cb7c90a1932e04fde6808a3ca9d3818fd64c/typing_extensions/src_py3/typing_extensions.py#L1157-L1159
It is clear that instantiating an object of a Protocol class bears no meaning since the protocol only details abstract specificiations and thus cannot be instantiated and this is enforced by typing_extensions when building a generic protocol class:
https://github.com/python/typing/blob/68e7cb7c90a1932e04fde6808a3ca9d3818fd64c/typing_extensions/src_py3/typing_extensions.py#L1233-L1251
To better …
=> Fix import error in Python 3.9

setup.py
The PR fixes a couple of problems in the `setup.py` file.
*First* the url to the repository was outdated, pointing at github.com/vlomonaco/avalanche which is currently extremely behind master branch.
*Second* it changes the `python_requires` to include the newly released [Python 3.10 version](https://www.python.org/downloads/release/python-3100/).
*Third* it adds to the list of `install_requires` many modules that must be installed in order to `import avalanche`, under penalty of ModuleNotFoundError.
Those are `torch`, `torchvision`, `gdown`.
As a sidenote the list of currently installed modules is huge, and I would consider setting those as [extras](http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies) and import them only in …
=> Fix setup.py problems: change outdated url, add modules to install_requires list

avalanche/training/strategies/icarl.py, avalanche/training/strategies/joint_training.py
- iCaRL now can work with benchmarks with a different number of classes in each (or some) experiences. 
- The Joint Training strategy can now be evaluated every epoch (or ever k epochs with k > 1). 
This PR fixes #807 and fixes #828
=> Fux bugs in iCaRL and Joint Training strategies

avalanche/logging/wandb_logger.py
This PR adds experience-change logging to the WandB logger by explicitly setting the step in `wandb.log(.)`.   This can be useful to have more meaningful visualizations in some of the plots.
Example:
is mapped to:
)
=> Add Experience-Change Logging to WandBLogger

avalanche/training/plugins/evaluation.py, tests/training/test_plugins.py
This PR adds a small feature to the EvaluationPlugin that allows to compute metrics outside MetricPlugins.
For example, let's assume that a strategy computes a loss function with many regularization terms, and we want to log each one separately. This is possible with the new API:
```
def criterion(self):
if self.is_training:
pred = self.teacher_targets.detach().max(dim=1)[1]
loss_activation = -self.teacher_features.abs().mean()
loss_ce = F.cross_entropy(self.teacher_targets, pred)
loss = loss_ce * self.oh + loss_activation * self.a
xp = self.clock.train_iterations
mval = MetricValue(origin=self, name='loss_ce', value=loss_ce.item(), x_plot=xp)
self.evaluator.publish_metric_value(mval)
mval = MetricValue(origin=self, name='loss_a', value=loss_activation.item(), x_plot=xp) …
```
=> evaluation can receive metric values from anywhere

avalanche/training/strategies/base_online_strategy.py, avalanche/training/strategies/strategy_wrappers_online.py, examples/online_naive.py
This PR initializes BaseOnlineStrategy. As discussed before, this is meant to be considered as a possible solution(and not necessarily the final soliton) for the implementation of online strategies. Three new files are added:
`avalanche/training/strategies/base_online_strategy` -> the base strategy for online strategies
`avalanche/training/strategies/strategy_wrappers_online.py` -> tried to avoid mixing strategy wrappers
`examples/online_naive` -> an example for testing
=> Initialize BaseOnlineStrategy

avalanche/benchmarks/generators/benchmark_generators.py, avalanche/training/plugins/early_stopping.py, tests/test_high_level_generators.py, tests/training/test_plugins.py, tests/unit_tests_utils.py
also adds class-balanced split for train/validation splits.
=> Early stopping & model checkpoint on iterations

avalanche/training/plugins/agem.py, tests/training/test_plugins.py, tests/training/test_strategies.py
This PR sets `num_workers=0` in `test_stratgies.py` and `test_plugins.py` to avoid data loading issues when running tests locally.
It also adds `num_workers` param to `AGEMPlugin`.
=> Set `num_workers=0` in all tests

avalanche/training/templates/base_sgd.py
This PR fixes a bug in `base_sgd` that triggers `_before_eval_exp` twice.
=> Minor bug fix in the `base_sgd` template 

avalanche/benchmarks/datasets/lvis/lvis_data.py, avalanche/benchmarks/utils/__init__.py, avalanche/benchmarks/utils/adaptive_transform.py, avalanche/benchmarks/utils/avalanche_dataset.py, tests/test_avalanche_dataset.py
This PR introduces the support for transformations that accept more than 1 parameter.
This is part of the effort for bringing a more solid object detection and segmentation support into Avalanche.
Multi-param transformations can be set as the `transform` parameter in `AvalancheDataset`. Transformations accept a variable amount of parameters (not limited to 2) so that this mechanism can be applied to datasets that return `x, y, z, j, k, ...` values, too. Task labels are never passed to transformations.
=> Support for transformations with N parameters.

avalanche/evaluation/metric_results.py, avalanche/evaluation/metrics/__init__.py, avalanche/evaluation/metrics/detection.py, avalanche/training/losses.py, avalanche/training/plugins/clock.py, avalanche/training/plugins/early_stopping.py, avalanche/training/plugins/lr_scheduling.py, avalanche/training/supervised/cumulative.py, avalanche/training/supervised/deep_slda.py, avalanche/training/supervised/joint_training.py, avalanche/training/supervised/strategy_wrappers_online.py, avalanche/training/templates/base_sgd.py, avalanche/training/templates/online_supervised.py, avalanche/training/templates/supervised.py, examples/detection_challenge.py, examples/tvdetection/lvis_eval.py
The metric implements two functionalities:
1. (optional) Saving model outputs to JSON file. The metric produces one file for each eval experience, where each file stores a list of dictionaries. Each dictionary is a model output.
2. Computation of metrics through LVISEvaluator object starting from model outputs. The metric returns a string. This point does not need 1. to work.
The code contains portions of code from #921 , adapted to fit the metric interface.
I am assuming to be able to access model outputs and targets through the usual `strategy.mb_output` and `strategy.mb_y` fields.
I just implemented the metric but I have not tested it in any ways.
=> Draft for LVIS detection metrics

avalanche/benchmarks/datasets/core50/core50.py, avalanche/benchmarks/datasets/openloris/openloris.py
- In both CORe50 and openloris, when the dataset were created with the field `train=True` the whole dataset is loaded (train + test set) and not only the train set as expected. Now with `train=True` only the training set is loaded. 
- In openloris only a portion of the dataset was loaded. Now the full dataset is loaded.
This PR fixes #928
=> Fix bugs in CORe50 and openloris datasets

avalanche/benchmarks/utils/avalanche_dataset.py, avalanche/training/templates/base_sgd.py, avalanche/training/templates/supervised.py
This PR brings the following fixes:
- Fixed an issue that prevented Windows users from using num_workers > 0
- `num_workers` was ignored in eval
- Added support for `persistent_workers` (since PyTorch 1.7.0)
Fixes #930
=> Various fixes and enhancements for the data loading process

avalanche/training/plugins/lr_scheduling.py, tests/training/test_plugins.py
This PR introduces the following options to the `LRSchedulerPlugin`:
- `granularity`: how often the scheduler's `step()` method is called. Valid values are 'epoch' (default) and 'iteration'
- `first_epoch_only`: if True, the `step()` method will be called only on the first epoch of each experience
- `first_exp_only`: if True, the `step()` method will be called only on the first training experience
In addition, `first_epoch_only` and `first_exp_only` can be True at the same time.
This also adds a lot of unit tests to validate the behavior with the new options.
=> LR Scheduler: added iteration granularity, exp0 and epoch0-only options

avalanche/training/plugins/agem.py
This closes #950 by setting to zero the num_workers in the replay buffer of AGEM.
If a larger number is used, the plugin will raise a warning to let you know you could incur in slowdown.
=> Set num workers to 0 in AGEM buffer dataloader

avalanche/evaluation/metrics/__init__.py, avalanche/evaluation/metrics/topk_acc.py
This adds all the sets of classes where it is possible to use the top-k accuracy in a similar way to the other metrics in the library.
- **TopkAccuracy** base class,
- **TopkAccuracyPluginMetric** plugin class,
- **MinibatchTopkAccuracy**, **EpochTopkAccuracy**, **RunningEpochTopkAccuracy**, **ExperienceTopkAccuracy**, **StreamTopkAccuracy**, **TrainedExperienceTopkAccuracy** classes
- **topk_acc_metrics** helper function
I used the k=3,5 for my experiments and it works.
=> Implementation of the top-k accuracy for Avalanche

avalanche/benchmarks/classic/clear.py, avalanche/benchmarks/datasets/clear/clear.py, examples/clear.py
We add a training example for CLEAR benchmark under "/examples/clear.py" and fixed bugs with earlier version of CLEAR benchmark generators, including:
(1) The task_labels should not be [0,...,0] but instead [0,1,...,9]
(2) The root should be appended to the image paths.
BTW, is there a way to make CLEAR visible on the avalanche website (will the webpage/API doc be refreshed automatically based on the code documentation)?
=> Add training example for CLEAR benchmark and fix root path issue

tests/training/test_strategies_accuracy.py, tests/unit_tests_utils.py
Now the accuracy tests inside `tests/training/test_strategies_accuracy.py` are deterministic and should not give any problem when run in the unit testing action. 
This is only a quick fix for the test inside the file reported, a comprehensive revision of all the test is needed, especially is accuracy or the results of experiments are taken into account, in order to make all the test deterministic. 
This PR closes #974
=> Deterministic test accuracy

avalanche/evaluation/metric_utils.py
The function `get_metric_name` now does not return the task label if `add_task` is False. The bug was due to the usage of `isinstance` function instead of `type` (bool is instance of int  but not an int type).
=> Fixed task label bug in metric name

avalanche/training/templates/base.py, avalanche/training/templates/base_sgd.py, avalanche/training/templates/online_supervised.py
First draft attempting to fix #989
=> Fix Templates type hints

avalanche/benchmarks/scenarios/generic_scenario.py, avalanche/benchmarks/scenarios/rl_scenario.py, tests/benchmarks/scenarios/test_rl_scenario.py
Proposal/first draft addressing the type hint issue which we currently have with CLStream and custom CLExperience (language server can't see their properties and methods).
An example of this is the [RLScenario](https://github.com/ContinualAI/avalanche/compare/master...NickLucche:refactoring-avalanche-rl#diff-2d765ee33fe8c41d986c0e95bb3cbbb972ad57c894905087fade0bf899636344R45) which now properly displays the return type of its train/eval streams (RLExperience).
I've also added task labels for eval experiences when creating an RLScenario.
=> Add Generics for new benchmark components

avalanche/training/plugins/cwr_star.py, tests/training/test_strategies.py
Fixed a bug in CWR star plugin. 
Before the fix the fist time a class in is encountered the number of patterns is not saved into the variable containing the past number of examples. 
Now the number of past examples is saved correctly.
=> Fix bug in cwr star plugin

avalanche/benchmarks/classic/clear.py, examples/clear.py, examples/clear_linear.py
1. We add a metric to our benchmark
2. We add an example on how to use the linear features of CLEAR to train and evaluate
=> Refactor the CLEAR training example

avalanche/benchmarks/scenarios/generic_scenario.py, avalanche/models/dynamic_modules.py, avalanche/models/pnn.py, avalanche/models/utils.py, avalanche/training/templates/online_supervised.py, avalanche/training/templates/supervised.py, profiling/replay_buffers.py, tests/benchmarks/scenarios/test_generic_scenario.py, tests/benchmarks/scenarios/test_rl_scenario.py, tests/test_helper_method.py, tests/test_models.py, tests/training/test_plugins.py, tests/training/test_supervised_regression.py
I needed a couple of changes to the dynamic modules.
two changes:
- `DynamicModule`s `adaptation` now uses `experience` instead of `dataset`. This should make things faster and support other benchmarks (RL, ex-model, OCL) where we may not have a dataset.
- output masking: some units of incremental/multihead classifiers are unused (e.g. if an experience contains classes 2 and 7, 8 units are created, 6 of which end up unused but trained anyway). Masking avoids training those units. Enabled by default but can be disabled.
=> Output mask for IncrementalClassifier and MultiHeadClassifier

.gitignore, avalanche/models/simple_cnn.py, avalanche/models/simple_mlp.py, docs/conf.py, docs/requirements.txt, environment-dev.yml
This PR is a result from discussion in Issue #886 and is inspired by PyTorch documentation ([here's an example](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html#:~:text=%3E%3E%3E%20m%20%3D%20nn.conv1d(16%2C%2033%2C%203%2C%20stride%3D2)))
- Update API docs footer to be 2022 (previously was 2021)
- Add examples to Simple CNN and SimpleMLP classes. It defaults to python syntax highlighting.
- Use the `sphinx_copybutton` extension to allow for users to quickly copy code blocks.
- The `sphinx_copybutton` extension can be installed in the conda environment with [these instructions](https://pypi.org/project/sphinx-copybutton/)
**Before**:
**After**:
=> Examples in docs

examples/ewc_mnist.py, examples/pytorchcv_models.py, examples/simple_ctrl.py, examples/standalone_metric.py, examples/synaptic_intelligence.py
Fix some minor issues if the following examples:
`ewc_mnist.py `
- Decay Factor must be None we using "separate" mode in EWC
`pytorchcv_models.py`
- Device was set to "CPU" manually, change it to use the argument
`simple_ctrl.py`
- Change the name of the metrics
- Add logger to the second strategy (line 115)
`standalone_metric.py`
- Add atribute _task_labels_ to metric update
`synaptic_intelligence.py`
- Remove _tb_log_exp_name_ from logger
=> Minor Fix in Examples

.gitignore, avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metric_utils.py, avalanche/evaluation/metrics/__init__.py, avalanche/evaluation/metrics/amca.py, avalanche/evaluation/metrics/class_accuracy.py, examples/eval_plugin.py, tests/test_metrics.py
This PR adds support for the Class Accuracy and Average Mean Class Accuracy metrics. This extends the #679 PR.
- Class Accuracy computes the per-class accuracy. It will do so separately for each task.
- The AMCA metric will compute its value for each `stream/task` and it will work only on the eval phase. In addition, it will automatically ignore periodic evaluations (this behavior can be customized).
Creating the AMCA metric has been quite rough, as this is the first stateful metric (others are computed and reset within the scope of a phase or less). @AntonioCarta @AndreaCossu can you give this a look? I introduced an extended metric mechanism and generalized the existing "value naming" procedure.
=> AMCA metric

avalanche/training/__init__.py, docs/gitbook/README.md
Hi guys, this is an interesting project you are working on. I've just started going through the code samples and stumbled upon some imports of `avalanche.training.strategies` which doesn't exist in the repo.
=> Outdated imports of `training.strategies` fixed in docstring and gitbook

profiling/online_strategy.py
This PR updates the online strategy profiler:
I removed the obsolete profilers and added `CProfile` to for more detailed profiling.
Current profilers:
`profile_online_naive_no_avl` -> online naive without Avalanche
`profile_online_naive_lazy_stream` -> online naive without Avalanche using lazy streams
`profile_online_avl` -> online (naive/er) using Avalanche
This is an example profiling output for Online ER:
It's interesting to see that almost half of the training time for the Online ER strategy is spent initializing datasets (most probably the `AvalancheConcatDataset` part):
** cumtime refers to the amount of time spent on the function itself + all its internal calls
=> Update online strategy profiler

avalanche/models/dynamic_modules.py, avalanche/models/helper_method.py
Speed up MultiTaskDecorator when `task_labels=None` by avoiding the recomputation of the hidden layers.
=> FIX MultiTaskDecorator

MANIFEST.in, setup.py
The next release should now include `csv_files` folder needed to build `MiniImagenetDataset`.
=> Packaged csv files for mini imagenet

tests/test_high_level_generators.py
Fixes a unittest that left text files in the project directory. Files are now created and destroyed in the system temp directory.
=> Minor fix to a unittest that left text files in the project directory.

avalanche/training/supervised/joint_training.py, tests/training/test_strategies.py
This PR fixes a minor bug in JointStrategy and updates strategy tests. 
The tests for multi-task versions of the following strategies are disabled for now because they do not work with dynamic modules:
- ewc_online
- rwalk
- synaptic_intelligence
- cope
- lfl
- mas
=> Fix `JointStrategy` and update strategy tests

avalanche/training/plugins/synaptic_intelligence.py
SI is not in alpha anymore, I removed the warning.
=> Removed warning about SI

avalanche/benchmarks/classic/ccifar10.py, avalanche/benchmarks/classic/ccifar100.py, avalanche/benchmarks/classic/ccub200.py, avalanche/benchmarks/classic/cfashion_mnist.py, avalanche/benchmarks/classic/cimagenet.py, avalanche/benchmarks/classic/cinaturalist.py, avalanche/benchmarks/classic/cmnist.py, avalanche/benchmarks/classic/comniglot.py, avalanche/benchmarks/classic/ctiny_imagenet.py, examples/lamaml_cifar100.py
Minor updates: this PR adds the optional parameter `class_ids_from_zero_in_each_exp` to some classific benchmarks set to False by default.
=> Add `class_ids_from_zero_in_each_exp`  to classic benchmarks

.github/workflows/environment-update.yml, .github/workflows/test-coverage-coveralls.yml, .github/workflows/unit-test.yml, install_environment.sh, install_environment_dev.sh, setup.py
After some internal discussion, we finally decided to drop the support for Python 3.6.
Python 3.6 is [discontinued](https://devguide.python.org/versions.html) since 23 December 2021. In addition, the support for Python 3.6 has been dropped in `coverage.py`, making it difficult to obtain coverage stats.
Apart from dropping the support from CI actions, this PR also updates the environment creation scripts to better support Python 3.10 and latest versions of CUDA.
=> Drop support for Python 3.6

avalanche/benchmarks/utils/data_attribute.py
Since `attribute.data[:]` returns a list, both special methods  return `str(self.data[:])`
=> Add repr and str special methods to DataAttribute

avalanche/benchmarks/datasets/torchvision_wrapper.py, avalanche/benchmarks/generators/benchmark_generators.py, avalanche/benchmarks/utils/classification_dataset.py, avalanche/benchmarks/utils/data.py, avalanche/benchmarks/utils/data_loader.py, avalanche/benchmarks/utils/deprecated.py, avalanche/benchmarks/utils/flat_data.py, avalanche/benchmarks/utils/transform_groups.py, avalanche/training/plugins/lwf.py, avalanche/training/regularization.py, avalanche/training/storage_policy.py, examples/lamaml_cifar100.py, examples/nlp.py, tests/benchmarks/scenarios/test_classification_scenario.py, tests/evaluation/test_image_samples.py, tests/test_high_level_generators.py, tests/test_nc_sit_scenario.py, tests/training/test_dictionary_mbatches.py
This PR adds a couple of changes to support datasets with dictionary elements.
- `AvalancheDataset` now allow dictionary elements
- BREAKING CHANGE: removed `collate_mbatches`. `ReplayDataLoader` does not need `collate_mbatches` anymore. It will use the collate from the original datasets.
- added test for dictionary datasets
- added huggingface example
=> huggingface and dictionary datasets support

avalanche/models/batch_renorm.py
The `r_max` and `d_max` variables are created as python floats but at some point become tensors on the wrong device. It seems to happen during or at the end of the testing phase. 
This fixes a crash due to heterogeneous devices when the AR1 method is used on the Core50 dataset and using a CUDA device to train the model after evaluation.
Here is the train-eval loop I'm using, it crashed after the second "Start of experience":
```python
for exp_id, experience in enumerate(benchmark.train_stream):
print("Start of experience ", experience.current_experience)
cl_strategy.train(experience)
print('Training completed')
print('Computing accuracy on the current test set')
cl_strategy.eval(benchmark.test_stream)
```
=> Ensures r_max and d_max are on the same device as the rest of the variables in BatchRenorm2D

.github/workflows/environment-update.yml
This adds checkpointing tests for environment update action.
Until PyTorch 1.13.1 is released, the checkpointing functionality will be broken (it's a bug on PyTorch 1.13.0).
Workaround: use PyTorch 1.12.*.
=> Add checkpointing tests for environment update action.

avalanche/benchmarks/utils/data.py, avalanche/training/templates/base.py, tests/test_avalanche_dataset.py, tests/training/test_strategies.py
- AvalancheDataset now accepts a single dataset instead of a list
- `eval_streams` now accepts a single stream instead of a list of streams
closes #1093 
closes #1156
=> FIX eval_streams

avalanche/benchmarks/utils/classification_dataset.py, avalanche/benchmarks/utils/data.py, avalanche/benchmarks/utils/flat_data.py, avalanche/training/plugins/rwalk.py, profiling/replay_buffers.py, tests/benchmarks/test_avalanche_dataset.py, tests/benchmarks/test_flat_data.py, tests/test_avalanche_classification_dataset.py, tests/training/test_strategies.py
improve the flattening process by recognizing when the same dataset occurs multiple times in the dataset list:
- added `_flatten_and_reindex` to improve flattening
- added a `__hash__` method for `AvalancheDataset` to recognize multiple dataset occurrences
@lrzpellegrini can you check this?
**Update**: fixed it. Now it's fast for the entire stream:
```
(split MNIST OCL with exp-size=5 samples, 6000 iterations total)
6003it [00:15, 389.10it/s]
ReservoirSampling Duration:  15.429586410522461
6003it [00:29, 205.35it/s]
ParametricBuffer (random sampling) Duration:  29.233972787857056
```
=> speed up dataset concat in OCL scenarios

avalanche/logging/interactive_logging.py, avalanche/training/templates/base.py, examples/online_naive.py, examples/online_replay.py, tests/training/test_online_strategies.py
- FIX an issue with eval stream initialization
- UPDATE interactive logger for online CL strategies
=> Issue Fix for OCL

avalanche/benchmarks/classic/cmnist.py, avalanche/benchmarks/classic/ex_model.py, avalanche/benchmarks/datasets/external_datasets/mnist.py, avalanche/benchmarks/utils/data_loader.py, avalanche/training/plugins/agem.py, avalanche/training/plugins/mas.py, notebooks/from-zero-to-hero-tutorial/03_benchmarks.ipynb, tests/evaluation/test_image_samples.py
The main change of the PR is related to the default MNIST dataset, which is now called `TorchMNIST`. The dataset does not return a PIL image anymore but directly a Torch tensor. 
This speeds up computation of strategies like A-GEM which access dataset items multiple times. The main bottleneck is due to the `ToPIL` transformation present in the default `MNIST` implementation (which requires a subsequent `ToTensor` transformation, thus increasing the total time).
=> Added TensorMNIST to speed up computation, minor fix in agem and mas

docs/README.md, docs/conf.py, docs/evaluation.rst, docs/models.rst
Added some missing classes from the APIdoc. Restored `no_class_attributes.rst` files. Currently any of the doc templates are much slower than the default one, which however generates lots of warnings.
=> First update of apidoc

avalanche/training/regularization.py, avalanche/training/supervised/__init__.py, avalanche/training/supervised/er_ace.py, avalanche/training/supervised/er_acl.py, tests/training/test_strategies.py
Started to implement the ER-ACE strategy from the "New Insights on Reducing Abrupt Representation Change in Online Continual Learning" paper [openreview link](https://openreview.net/forum?id=N8MaByOzUfb).
The implementation is still not 100% ready but I need your input on a few things. 
First of all, I have created two strategies. One for the online setting (using Online Scenario), and one for the non online setting. It felt a bit bad to do this since they are basically doing nearly the same thing (the only difference is how the replay buffer is updated), but I don't really know how to do things differently. Do you think it's mandatory to have two different strategies for the two different settings (as it is done for Naive and OnlineNaive) ? If you have a better Idea of how to split …
=> Adding ER-ACE strategy

avalanche/evaluation/metrics/__init__.py, examples/detection.py
Fixed an error that was raised when installing avalanche without the optional detection dependencies.
I'm afraid we'll need to create ad hoc tests to prevent similar problems in the future.
=> Detection dependency fix

avalanche/training/plugins/cope.py
Playing around with this plugin to see if a change to ReplayDataLoader would fix it, I noticed the problem was coming from a different cause. self.replay_mem: dict was used in parallel to a normal storage policy but was never updated, I replaced that by using the examplars from the storage policy instead. Running it on the continual-learning-baselines repo for split mnist gives the expected result written in the table of 93%.
Otherwise I think the plugin is not affected by the ReplayDataLoader bug to the exception that the interactive logger shows growing number of iteration for one epoch. But the plugin has a maximum number of iteration parameter.
=> Fixed cope plugin

avalanche/training/plugins/__init__.py, avalanche/training/plugins/from_scratch_training.py, avalanche/training/supervised/strategy_wrappers.py, examples/from_scratch_training.py
This PR adds a new plugin called FromScratchTraining that resets the model's weights and optimizer state after each training experience. It is used as a baseline for comparison with sequential fine-tuning in some papers. 
Minor: we can change the plugin's name if it's wordy. Another potential name could be: "StrategyResetter"
=> Add `FromScratchTrainingPlugin`

avalanche/logging/wandb_logger.py
Values of type TensorImage were being treated as unsupported despite having their own code branch line 186.
=> Fixed TensorImage being treated as an unsupported logging type

avalanche/benchmarks/utils/data_loader.py, avalanche/training/plugins/replay.py, tests/benchmarks/test_replay_loader.py
Linked to issue #1274. I think this should  be enough for the fix, however I would prefer to wait for confirmation that this does not break anything. As far as I understood, loader_data is a dictionnary containing data for the potential multiple tasks present in the current experience. So, taking the maximum length over just this dictionnary should ensure we see all the data from current task, and loop on the other task dataloader if they are of unequal size. However, we don't want to take the maximum lenght also from replay loader since it can lead to the bug described in the above issue.
I also removed the part where the length of the memory buffers were added to the loaders used for length estimation.
=> replay fix proposition

avalanche/benchmarks/scenarios/online_scenario.py, avalanche/training/templates/common_templates.py, avalanche/training/templates/observation_type/online_observation.py
This PR update template docstring and OnlineObservation. 
The changes in the OnlineObersvation class now enable training models with dynamic modules in online strategies. Model adaptation is removed for each sub-experience, and instead, model adaptation and optimizer reset happen only in the boundary sub-experiences. Related to issue #1197.
=> Update OnlineObservation and Template Docstrings

avalanche/training/regularization.py, avalanche/training/supervised/er_ace.py
As mentioned in continual learning baselines repo, I simplified the ER-ACE criterion so that it does not track the old and current classes anymore but only considers classes in the current batch as current classes. That way the method does not have to be aware of the stream structure, as it is done in the paper. The results are not changed drastically, sometimes better sometimes worst but not a big difference overall.
=> ER-ACE criterion simplification

avalanche/benchmarks/utils/classification_dataset.py, avalanche/benchmarks/utils/data_loader.py, avalanche/benchmarks/utils/transform_groups.py, avalanche/training/plugins/evaluation.py, tests/test_dataloaders.py
Hello, In the current version of avalanche (0.3.1) setting num_workers > 0 in the train function of a strategy causes a crash.
In my case the reason for this was a number of lambda functions in dataset definitions, which cannot be pickled. Since PyTorch relies on pickle for multiprocessing this prohibits parallelisation in data loading.
This pull request includes a simple fix, although admittedly not a very beautiful one. Unfortunately I do not know the library well enough yet to propose a better solution. Nonetheless I hope that this is helpful to you.
Thank you for all the work you do!
Best wishes,
Daniel
=> replace lambda functions with pickle compatible equivalent.

avalanche/benchmarks/utils/data_loader.py
Hello,
setting prefetch_factor to anything else than 2 caused the program to crash during length estimation of the dataset.
=> Allow setting prefetch_factor for multiprocessing

avalanche/benchmarks/utils/data.py, avalanche/benchmarks/utils/data_attribute.py, avalanche/training/storage_policy.py, avalanche/training/supervised/__init__.py, avalanche/training/supervised/der.py, tests/benchmarks/test_data_attribute.py, tests/training/test_strategies.py
I added the DER strategy here. Below I list some implementations details and choices that we can change potentially.
- About the use of transformations: For now, I do not use transformations by default on the current data, because in avalanche this is not suppose to be a choice from the strategy but rather one from the benchmark. However, the use of input transformations is a part of the DER method, so it should be either triggered when using it in what case the actual DER will happen, or used without input transformations in what case transformations will be applied only on the buffer data.
- To store the data, I use a derived version of ClassBalancedBuffer which additionally stores the logits of the memory samples so that they can later be replayed. To do this, I use a classification …
=> Added DER strategy

avalanche/training/plugins/mir.py
Maybe wait before merging since this is linked to issue #1340 and @HamedHemati also reported a huge slowdown. If I find out where it comes from we might fix it also in this PR.
=> fixed mir unused subsample argument

avalanche/benchmarks/datasets/clear/clear.py, avalanche/benchmarks/datasets/clear/clear_data.py, examples/clear.py, examples/clear_linear.py
According to the [CLEAR official wiki](https://linzhiqiu.gitbook.io/the-clear-benchmark/documentation/download-clear-10-clear-100), the download path is slightly changed although the previous one is still working now. Moreover, they removed other features except moco_b0. I changed it accordingly.
=> Refactor CLEAR Benchmark based on the official webpage

avalanche/benchmarks/utils/data.py, tests/test_avalanche_classification_dataset.py
When calling .freeze_transfroms() on a dataset all child datasets will also freeze their transforms now.
=> Fix for Issue #1353

avalanche/benchmarks/classic/ccifar10.py, avalanche/benchmarks/classic/ccifar100.py, avalanche/benchmarks/classic/ccub200.py, avalanche/benchmarks/classic/cfashion_mnist.py, avalanche/benchmarks/classic/cimagenet.py, avalanche/benchmarks/classic/cinaturalist.py, avalanche/benchmarks/classic/cmnist.py, avalanche/benchmarks/classic/comniglot.py, avalanche/benchmarks/classic/ctiny_imagenet.py
A small fix so that we can forward this option to the benchmark creation. It was not the case yet.
=> Forward class_id_from_zero_in_each_exp to nc_benchmark in classical benchmarks

avalanche/benchmarks/generators/benchmark_generators.py, avalanche/evaluation/metrics/cumulative_accuracies.py, tests/test_high_level_generators.py
The recent typing fixes switched the factory validation and data incremental generators to a generic DatasetScenario, which is problem-agnostic. With this PR, we try to return a benchmark of the same class of the input benchmark, allowing experiences to be created with the correct fields.
Fixes #1371
=> Fix issue #1371

avalanche/evaluation/metrics/topk_acc.py, tests/test_metrics.py
Fixes an issue with torchmetrics >= 0.11.0 and the top-k accuracy
Fixes #1232
=> Fix issue #1232. Added unit tests.

avalanche/benchmarks/scenarios/online_scenario.py
Minor fix: this PR adds the `shuffle` parameter to `OnlineCLScenario` (set to True by default) to allow control for sample orders in the sub-experiences.
=> Sample Order in OnlineCLScenario

avalanche/training/templates/base_sgd.py
With the addition of this variable, you can decide to keep the graph by setting `strategy.retain_graph = True` so that plugins can do their own backward pass after to the one triggered automatically without having to execute the forward pass again.
Unsatisfactory alternatives:
- subclass BaseSGDTemplate and change the implementation of its `backward()` method
- monkey patch the `backward()` method
- call `strategy.forward()` each time a second backward pass has to be made in the same iteration
Note that perhaps the name of this variable should be changed to something else.
=> Add a variable to control whether to retain the graph or not in the backward pass

avalanche/training/supervised/expert_gate.py, avalanche/training/templates/observation_type/batch_observation.py
This clarifies the role of self.make_optimizer function that should be call whenever resetting the optimizer.
I now call it instead of reset_optimizer in expert gate
I also changed the make_optimizer function so that it changes the optimized_params_id in place so that the user does not have to care about them, and that the behaviour from check_model_and_optimizer is clearly separated from the one of make_optimizer (adaptation + make_optimizer but no more setting of optimized_param_id).
=> FIX: Make optimizer now changes optimized_param_id in place

avalanche/evaluation/metrics/cumulative_accuracies.py, avalanche/training/supervised/expert_gate.py, avalanche/training/templates/base_sgd.py, avalanche/training/templates/observation_type/batch_observation.py, tests/test_metrics.py
When access_task_boundaries = False, the model adaptation was not called, I fixed it.
@AntonioCarta Another thing that I could fit there -> We had spoken about an option to reset the optimizer state or not. Right now by default it's False but their is no real way to change it apart when calling self.make_optimizer. Should I add this option to the SupervisedTemplate ?
Also I would like to fix the unit tests that don't pass sometimes but I'm not able to reproduce the bugs locally ...
=> BugFix OnlineTemplate missing model adaptation call

avalanche/models/ncm_classifier.py, avalanche/models/scr_model.py, avalanche/training/supervised/icarl.py, avalanche/training/supervised/supervised_contrastive_replay.py, avalanche/training/templates/base_sgd.py, tests/test_models.py
The NCM Classifier was quite cumbersome to use. Now it explicitly keeps a dictionary of means for each class and has a method to update the means. 
The means are vectorized in a tensor after each update.
Tests and strategies using NCM have been updated.
=> NCM Classifier uses dictionary and can update means

avalanche/training/plugins/gem.py
Not shuffling the dataset has a large reduction in performance, since it may lead to an uneven distribution of samples per class within a task.
Using a class-balanced buffer would solve this. It is something we should consider for this kind of strategies. 
For balanced datasets, this PR should fix the issue.
=> Shuffling dataset when updating GEM memory

avalanche/training/templates/base_sgd.py
Before that, when calling
strategy.train(experience, eval_streams=[scenario.val_stream], drop_last=True)
The drop_last argument was used both in the training and in the evaluation dataloader. This is a quickfix to fix this behavior, it would be nice to find a better way of distinguishing kwargs that are forwarded to eval/train loaders, or even to functions outside of loaders.
=> removed drop_last forwarding from make_eval_dataloader

avalanche/benchmarks/utils/data_attribute.py, avalanche/benchmarks/utils/flat_data.py, avalanche/benchmarks/utils/utils.py, tests/benchmarks/test_flat_data.py
Lazy indices for FlatData to support faster operations.
=> faster indices for FlatData with lazy operations

avalanche/models/ncm_classifier.py, avalanche/training/supervised/icarl.py, tests/test_models.py
Now NCM allows to replace all the means. This is useful in iCarl, where means are replaced after every experience.
=> Added NCM replace dictionary and used in icarl

avalanche/evaluation/metrics/cumulative_accuracies.py, avalanche/training/supervised/der.py, avalanche/training/supervised/er_ace.py, avalanche/training/templates/observation_type/batch_observation.py, avalanche/training/utils.py, tests/test_metrics.py
I noticed cumulative accuracy was not working when the benchmark option class_idx_from_zero_from_first_exp was not activated. I fixed it. I also added some functions that I was using here and there to the training/utils.py as well as a new function to detect if the experience is at task boundary (and thus needs to be used for adaptation) depending on several attributes (access_task_boundaries, is_fist_subexp, is OnlineCLExperience etc.. ).
=> small refactor and cumulative accuracy fix

avalanche/models/dynamic_modules.py, avalanche/models/ncm_classifier.py, avalanche/training/losses.py, avalanche/training/supervised/icarl.py, tests/test_models.py
The behavior of TrainEvalModel was not always consistent and the classifier sometimes failed to switch.
I brought back the DynamicModule version, this fixes iCarl performance.
=> Fixed icarl by converting back TrainEvalModel to DynamicModule

avalanche/benchmarks/utils/classification_dataset.py, avalanche/benchmarks/utils/data_loader.py, avalanche/benchmarks/utils/detection_dataset.py, avalanche/training/supervised/naive_object_detection.py, avalanche/training/templates/update_type/sgd_update.py, tests/test_dataloaders.py
As part of the effort to add support for FFCV data loading, this PR brings an overall change in the way data loaders are created.
Avalanche data loaders are used to return batches which are the concatenation of smaller mini-batches from multiple datasets. 
Up to now, this was accomplished by:
- Creating a data loader for each dataset (each with the same parameters!)
- Manually looping over all loaders, fetching the sub-mini-batches  
- Collate the sub-mini-batches before returning them (in the main thread!)
This led to issues regarding `num_workers` (which were spawned for each sub-dataset thus leading to spawning `N * num_workers`), bottlenecks related to the collate on the main thread, etc, not to mention that the code of each loader replicated operations already implemented in other …
=> Streamline data loaders

avalanche/benchmarks/utils/data_loader.py, tests/benchmarks/test_replay_loader.py
This PR fixes a couple of issues with the new data loading system:
- If the size of a dataset is < minibatch size, the data loader no longer raises `StopIteration`
- Managed a corner case in which the size of termination dataset < minibatch size, but the loader was not terminating immediately
=> Fixed issues with 0 length samplers

avalanche/models/dynamic_modules.py, avalanche/training/plugins/rar.py
When testing the RAR implementation using a model with `IncrementalClassifier` class, @AlbinSou found a new error.
The problem arises between an incompatibility between `IncremetnalClassifier` and the `feature_extraction` functions from pytorch. Because of this, I changed the mask function in the `IncrementalClassifier` class to be an in_place operation. This solves the first problem.
A second problem was a `KeyError` problem with `optimizer.state_dict()`. Because of this, I simplified the RAR implementation. This can help with the performance but sometimes take more time to run.
=> Fix integration with IncrementalClassifier

avalanche/models/ncm_classifier.py
Adds an adaptation at evaluation for NCM so that it fills class_means_dict with torch.zeros (default behavior for non-pre-existing classes).
Previously using eval_every=1 would fail unless all classes are present in the class_means_dict. Now it still fails for the first step (no classes in dict) since the feature size is unknown when no feature vectors are present. But it does not fail anymore for other steps.
=> turn ncm to dynamic module that adapts with 0 vectors at evaluation

avalanche/benchmarks/classic/core50.py, avalanche/evaluation/metrics/checkpoint.py, avalanche/logging/text_logging.py, avalanche/logging/wandb_logger.py, avalanche/training/plugins/ewc.py, examples/multihead.py, examples/wandb_logger.py, tests/test_core50.py, tests/test_models.py
The following fixes have been ported from PR #1397. Here are taken as stand-alone as they weren't strictly related to the scope of the PR.
This PR:
- Fixes #774
- Allows EwC to accept num_workers (supersedes #1310)
- Allows W&B to log the weights checkpoint (supersedes #706)
- Prevents the creation of a unit test file in the main folder
=> Various fixes and improvements

avalanche/benchmarks/scenarios/lazy_dataset_sequence.py
A simple fix to speedup benchmark creation and stream iteration.
The impact is greatly noticeable in long benchmarks (such as SplitImagenet, n_experiences=1000), where the iteration time on the training stream drops from 1h to 1m. I also tried other optimizations regarding FlatData, but this seems to be the most straightforward solution.
=> Speedup for long benchmarks iteration

tests/benchmarks/scenarios/test_classification_scenario.py
Add additional checks to confirm that classification fields such as `classes_in_experience` and `classes_in_this_experience` return unique ints and not tensors.
Closes #1104
=> Extend unit tests to confirm resolution of #1104

avalanche/training/supervised/lamaml_v2.py, avalanche/training/templates/base_sgd.py, examples/detection.py, examples/detection_lvis.py, setup.py, tests/benchmarks/scenarios/test_rl_scenario.py
After some testing, it seems that we can remove the runtime dependency on setuptools.
This switches the runtime version checks (previously done using setuptools `pkg_resources`) to `packaging`, as `pkg_resources` is deprecated.
Minor fix for `rl` unit tests, that raised an error if an optional dependency could not be found.
=> Remove setuptools version constraint

avalanche/models/ncm_classifier.py, tests/test_models.py, tests/training/test_strategies.py
NCM now supports forward pass even when no class mean is provided. NCM automatically initializes class means to zero based on the largest class found in the eval dataset during eval adaptation.
=> Fix for NCM forward pass when no class mean is present yet

avalanche/models/packnet.py, avalanche/training/supervised/strategy_wrappers.py, tests/models/test_packnet.py
- The PackNet plugin is implemented inline with the PackNet module implementation. Is that okay?
=> Implement PackNet

avalanche/training/templates/observation_type/batch_observation.py, avalanche/training/utils.py
Two fixes,
One is some useless code that was left in the batch_observation. This code was slowing down a bit in the case of using an online setting with access to task boundaries. I had mistakenly left this part of code when switching to using util function at_task_boundary.
Another is about some formatting and changing one feature in the at_task_boundary function. So far the function was only using is_first_subexp attribute which was leading to some problems when using it in after_training_task, it was not detecting the boundary if the experience was the last experience of the task. Now it is detecting the boundary both right before the shift and right after the shift.
=> Some minor fixes in batch_observation and utils

avalanche/benchmarks/utils/ffcv_support/center_crop.py, avalanche/benchmarks/utils/ffcv_support/ffcv_transform_utils.py, avalanche/training/supervised/naive_object_detection.py, avalanche/training/templates/problem_type/supervised_problem.py, examples/ffcv/ffcv_enable.py, examples/ffcv/ffcv_enable_rgb_compress.py, examples/ffcv/ffcv_try_speed.py
Minor FFCV support improvements:
- Add CenterCrop transformation to support variable-resolution datasets when loaded with CenterCrop as the first transform (a decoder that achieves something similar already exists in FFCV, but its behavior is not aligned with the torchvision one)
- Fix the FFCV try_speed example
- Add `non_blocking=True` in `_unpack_minibatch` of supervised problem and object detection
=> Ffcv improvements

avalanche/training/losses.py, avalanche/training/regularization.py, avalanche/training/templates/base_sgd.py, tests/training/test_losses.py
I added a criterion that is very important when considering exemplar free scenarios, and only considers the learning of the new task. It's like a multitask learning criterion except this time we don't have task labels so the model outputs the full logits but when not using exemplars we want to update only the last head with the cross-entropy loss in order to avoid task-recency bias.
I personally needed this criterion to use LwF in the class incremental learning scenario but I think that in general it is useful whenever using functional regularization in CIL in the examplar free setting.
Another change that I introduced is more of a personal choice and I need your input on that. I noticed that many criterias were implemented as plugins because they need to access at some point some info …
=> Added NewClassesCrossEntropy criterion and automatic criterion plugin

avalanche/benchmarks/utils/utils.py, tests/benchmarks/utils/test_avalanche_classification_dataset.py
`list(torch.Tensor) ` doesn't convert Tensor to list of scalars, but to list of Tensors.
I checked this is True for pytorch versions 1.12 and 2.0
```
[ins] In [6]: a = torch.Tensor([0,1])
[ins] In [7]: a.tolist()
Out[7]: [0.0, 1.0]
[ins] In [8]: list(a)
Out[8]: [tensor(0.), tensor(1.)]
```
That lead to the KeyError when I tried to used combined pytorch datsets, like this
```
if args.reproduce_bugs:
fmnist_test.targets += 10
fmnist_train.targets += 10
full_test = mnist_test + fmnist_test
full_train = mnist_train + fmnist_train
n_classes = 20
else:
full_test = mnist_test
full_train = mnist_train
n_classes = 10
benchmark = nc_benchmark(
full_train,
full_test,
n_experiences=n_classes // 2,
task_labels=list(range(10)),
)
```
I probably will open an issue, because the same probably will repeat …
=> proper conversion of Tensor to list

avalanche/models/__init__.py, avalanche/models/cosine_layer.py, avalanche/models/fecam.py, avalanche/training/plugins/__init__.py, avalanche/training/plugins/update_fecam.py, avalanche/training/plugins/update_ncm.py, tests/models/test_models.py, tests/training/test_update_utils.py
I start this PR but it's not finished. Feel free to discuss the things that should be changed. 
For now, here is what I added
- FeCAM (NCM-like but using malahanobis distance (stores per-class covariance matrices) [arxiv](https://arxiv.org/abs/2309.14062)
- FeCAM update utils (current, memory and oracle)
- NCM update utils (current, memory and oracle)
- Cosine Linear first draft
Here is what I want to add:
- Tests for FeCAM
- Tests for all the update utils
- Change Cosine Linear so that it can have new number of new classes (for now it handles only cases with same number of classes in each exp)
- Test for Cosine Linear
- FeatureAdapters [arxiv](https://arxiv.org/abs/2004.00713) (for NCM, for now could not make it work for LinearSVC) + tests
- Resnet18 adapted for Cifar and Tinyimagenet …
=> CIL Examplar Free components

avalanche/models/bic_model.py, avalanche/training/plugins/bic.py, avalanche/training/storage_policy.py, tests/benchmarks/scenarios/test_task_aware.py
This PR is a major re-implementation/global fix for [BiC (paper)](https://openaccess.thecvf.com/content_CVPR_2019/papers/Wu_Large_Scale_Incremental_Learning_CVPR_2019_paper.pdf)
The implementation found in Avalanche (and in other CL libraries as well) has various issues, mainly connected to the understanding of how the algorithm works. It's an honest mistake that I made too when reading the paper.
The official implementation of BiC can be found here (TF 1.x :/ ): https://github.com/wuyuebupt/LargeScaleIncrementalLearning/tree/master
BiC works like that:
1. Distillation phase: classic training loop with distillation loss (on logits of old classes) + classification loss (logits of old and new classes)
2. Bias correction phase: learn alpha and beta correction parameters for new classes
The …
=> Major BiC fix/reimplementation

avalanche/benchmarks/classic/openloris.py, avalanche/benchmarks/classic/stream51.py, avalanche/benchmarks/datasets/lvis_dataset/lvis_dataset.py, avalanche/benchmarks/datasets/mini_imagenet/mini_imagenet.py, avalanche/benchmarks/scenarios/deprecated/lazy_dataset_sequence.py, avalanche/benchmarks/scenarios/generic_scenario.py, avalanche/benchmarks/scenarios/online.py, avalanche/benchmarks/utils/collate_functions.py, avalanche/benchmarks/utils/dataset_definitions.py, avalanche/benchmarks/utils/dataset_utils.py, avalanche/benchmarks/utils/transform_groups.py, avalanche/distributed/distributed_helper.py, avalanche/evaluation/metric_definitions.py, avalanche/evaluation/metrics/confusion_matrix.py, avalanche/evaluation/metrics/detection.py, avalanche/evaluation/metrics/images_samples.py, avalanche/evaluation/metrics/labels_repartition.py, avalanche/evaluation/metrics/mean_scores.py, avalanche/training/plugins/lr_scheduling.py, avalanche/training/templates/strategy_mixin_protocol.py, environment-dev.yml, environment.yml
- Moves many imports from typing-extensions to typing. This also fixes the multiple inheritance issue (at least on Python 3.8). Only TypeAlias imports are kept because they are needed for Python<3.10.
- Removes ctrl-benchmark from the conda definition file due to ctrl-benchmark having a strict torch<2 dependency
- This should also fix the recent issues in the CI: by installing ctrl-benchmark, PyTorch was replaced with a cuda pip version (thus ignoring conda's cpuonly).
Related: https://discuss.pytorch.org/t/modulenotfounderror-no-module-named-torch-dynamo/193014
=> Improve support for PyTorch 2.* and Python>=3.8

requirements.txt
See: https://github.com/quadprog/quadprog/pull/43
=> Fix install issue of quadprog when using Python 3.11

avalanche/benchmarks/scenarios/__init__.py, avalanche/benchmarks/scenarios/dataset_scenario.py, avalanche/benchmarks/scenarios/supervised.py, avalanche/benchmarks/scenarios/validation_scenario.py, avalanche/models/dynamic_modules.py, tests/benchmarks/scenarios/test_dataset_scenario.py, tests/training/test_plugins.py
@AlbinSou this should fix your issue.
Closes #1597
=> fix issue #1597

avalanche/training/supervised/lamaml_v2.py
Fix a bug in lamaml v2 buffer usage
=> LaMAMLv2 buffer now uses subset instead of indexing

docs/benchmarks.rst, extra_dependencies.txt
I removed some old doc references to functions that are not present in the benchmarks module anymore.
ctrl-benchmark package does not support pytorch2 and the project is archived. the package is now installed through a separate installation tag, ctrl.
=> Removed old functions in doc, move ctrl-benchmark to separate tag

avalanche/models/dynamic_modules.py, avalanche/models/fecam.py, avalanche/models/ncm_classifier.py, avalanche/models/pnn.py, avalanche/models/utils.py, notebooks/from-zero-to-hero-tutorial/02_models.ipynb, tests/models/test_models.py
I tried to implement the changes that would fix bugs described in Issue #1591 and also allow users to use Dynamic modules more easily outside of avalanche strategies.
To do so, I made several major changes.
- Remove old avalanche_model_adaptation method and replace it with a new version which does things differently. Instead of iterating on all modules, it iterates only on childrens, and does so recursively in order to explore the whole hierarchy. It still iterates on the hierarchy of nn.Modules and catches DynamicModules to adapt them just like before.
- Added a method adapt() to dynamicmodule that will call the new "avalanche_model_adaptation" on itself and recursively on it's submodules
- Added an _auto_adapt attribute to all DynamicModules that triggers or not the adaptation inside …
=> Changes in Dynamic Modules

avalanche/benchmarks/scenarios/task_aware.py, tests/benchmarks/scenarios/test_task_aware.py
Hello, I found a bug in  the `task_incremental_benchmark` generator. Even with the MNIST example in the notebook "_03_benchmarks.ipynb_" `exp.task_labels` is a set not a list as the train method expects.
I think the problem is here, where we convert the set in the list only for the `task_label` attribute: https://github.com/ContinualAI/avalanche/blob/0d6f7155446b2b4b25b33b8e7d21284ca8d7d06a/avalanche/benchmarks/scenarios/task_aware.py#L89-L105
The set is never converted into a list for the attribute task_labels and in in this method we use the indexing which is not supported by a set: https://github.com/ContinualAI/avalanche/blob/0d6f7155446b2b4b25b33b8e7d21284ca8d7d06a/avalanche/evaluation/metric_utils.py#L249-L275
Below you can find the small fix + an assert I added in the TaskAware …
=> task_labels experience attribute type fix: now it is a list, not a set

avalanche/training/templates/base_sgd.py, avalanche/training/templates/problem_type/supervised_problem.py, examples/custom_datasets.py
allows to use benchmarks without task labels (e.g. `class_incremental_benchmark`) in Avalanche strategies
=> support benchmark without task labels in avalanche.strategies

avalanche/training/plugins/__init__.py, avalanche/training/plugins/il2m.py, avalanche/training/supervised/strategy_wrappers.py, docs/training.rst, tests/training/test_strategies.py
Implementation of the class-incremental method "Incremental Learning with Dual Memory" (IL2M).
=> Added IL2M strategy

avalanche/evaluation/metrics/detection.py
Added _FlatDataWithTransform to recursion condition of the function "get_detection_api_from_dataset". 
Previously it recursed when the dataset is an instance of (Subset, AvalancheDataset, ConcatDataset),
but _FlatDataWithTransform can be given as "dataset" parameter in the recursion. (examples/detection_lvis.py)
=> Fixed detection api retrieval from dataset
